- hosts: all
  gather_facts: false
  vars:
    ansible_connection: redhat.cmeyers.my_connection
    ansible_my_connection_connectionvar: 'from_play'
  tasks:
    - debug:
        msg: "I am host '{{ inventory_hostname }}'"

    - raw: echo 'hello world'
      register: connection_out

    - debug:
        msg: "connection plugin test {{ connection_out.stdout }}"

- hosts: localhost
  gather_facts: true
  tasks:
    - redhat.cmeyers.my_action:
    - redhat.cmeyers.my_module:
    - debug:
        msg: "my lookup is {{ lookup('redhat.cmeyers.my_lookup') }}"
    - debug:
        msg: "{{ 'my_filter' | redhat.cmeyers.my_filter }}"
    - stat:
        path: "fact_cache/localhost"
      register: st
    - debug:
        msg: "Fact cache localhost file has a size of {{ st.stat.size }}"
  roles:
    - redhat.cmeyers.my_role
