---
- hosts: localhost
  gather_facts: false
  vars:
    employee_name: "cmeyers"
    termination_protection: no
    ec2_filters:
      "tag:Ice": "jenkins-nightly-tower-cluster-haproxy-ssl-devel-ansible-stable-2.7"
      "instance-state-name": "running"

  tasks:
    - name: Find instances
      ec2_remote_facts:
        region: "us-east-1"
        filters: "{{ ec2_filters }}"
      register: ec2_instances

    - name: Rename Instances
      ec2_tag:
        resource: "{{ item['id'] }}"
        region: "us-east-1"
        tags:
          Name: "{{ employee_name }}_{{ item.tags.Name }}"
      when: not item.tags.Name.startswith(employee_name + '_')
      with_items: "{{ ec2_instances.instances }}"

    - name: Protecting instances
      ec2:
        instance_ids: "{{ ec2_instances | json_query('instances[].id') }}"
        region: "us-east-1"
        state: running
        termination_protection: "{{ termination_protection }}"
      register: results

    - name: Output Protected Instances
      debug:
        msg: "{{ results }}"
